    !----------initialization-------------!
    subroutine ini
    use the_whole_varibles
    implicit none
    integer:: n_pic,I_r,I_z
    real*8  b0_set,r_cyclotron,irf_set!,vi_mean,Ti_mean,t_lz
    call start_ftime

    !-----------------------discharge set-------------------------------!
    iswitch_display=  1; !1--display the running state on screen; 0--display nothing, suitable for backstage running. 
    iswitch_mcc=1  !0-monte carlo collsion off, 1-on
    iswitch_ji_on=1 !1-include ion current Ji and electron current Je in FDFD; 0-only include Je (not include Ji)
    
    !iswitch_antenna_type= 0, single loop  
    !                    =-1, left helical 
    !                    = 1, right helical
    !                    = 2, half loop 
    !                    = 3, Nagoya type-III
    iswitch_antenna_type=0      

    !i_switch_B0=1: uniform b0_ci you specificly set;
    !i_switch_B0=2: load B0 from txt files;
    !i_switch_B0=3: B0 field generated by coils (subroutine background_b0)
    i_switch_B0=3;
    b0_set=0.4; !T. note: used only when i_switch_B0=1, i.e., i_switch_B0=2 or 3--not use;
    
    irf_set=10; !A    
    max_density_set=1e19   !m-3, maxium initial plasma density
    ti_ini=3;   !eV  !initial teamperature of ion
    te_ini=3. !eV

    n_pic=6 !total number of picture to record, i.e. record data at every td/n_pic
    td=3e-3; !s
    t_power_on=1e-5 !s, note here, important: time to switch on Erf. 
    dt_trf=1e-2;      ! dt (Trf)
    dt_run_fdfd=10*trf
    t_show=5*trf; !trf
    t_rec=1*trf   !trf
    t_rec_trajectory=trf/5   !trf

    pn=1.0    ! Pa
    iswtich_inner_dipole=0; !0- no inner dipole field; 1-with

    z_inject=0.5; ! m,  central axial position of inject particle
    width_ne_r=0.025 !rw 0.015 !energy conservation
    width_ne_z=0.4  !zw 0.4 !energy conservation
    width_ne_source_r=width_ne_r
    width_ne_source_z=0.1


    call fdfd_ini
    call grid
    call antenna
    call set_particle_inject_distribution
    call mcc_constant


    if(i_switch_B0==2)then
        call load_B0
    elseif(i_switch_B0==3)then
        call background_b0
    else
        b0_DC(:,:,1)=0.
        b0_DC(:,:,2)=0.0D0
        b0_DC(:,:,3)=b0_set;
        b0_DC(:,:,4)=b0_set;
    endif
    B_resonance=2*pi*frequency/q_mass
    I_z=minloc(abs(za-z),1);
    I_r=2;
    if(i_switch_B0==1)then
        B0_correction_factor=0.
    else
        B0_correction_factor=B_resonance/b0_DC(I_r,I_z,4)
        b0_DC=b0_DC*B0_correction_factor !set resonant B0 at z=za
    endif
    bz_max=maxval(b0_DC(1:2,1:nz,4))

    te_ave=te_ini
    ti_ave =ti_ini
    om=2*pi*frequency;
    omc2=(om/c)*(om/c)
    iom=i*om*mu0
    resistance=1   ! ohm, antenna resistance
    power_Joule=irf_set**2*resistance;  ! W
    i_now=irf_set
    nn=3.22e16*pn/133.322*cm3; ! ann0=nn; !m-3
    dt=dt_trf*trf;
    vi_ex=sqrt(qe_abs*ti_ini/mi);
    ve_ex=sqrt(qe_abs*te_ini/me);
    ek_ion_2D=ti_ini*1.5
    t_rec_pic=td/real(n_pic)

    call rec_para
    open (unit=42,file='1time_average.dat',status='unknown',iostat=ierror)
    open (unit=43,file='1time_trajectory.dat',status='unknown',iostat=ierror)
    end subroutine ini



    subroutine rec_para !record parameters
    use the_whole_varibles
    implicit none
    real*8:: para(1:40)=0
    para(1)=nr;para(2)=nz;para(3)=max_density_set;para(4)=density_ave;
    para(5)=rs;para(6)=dr;para(7)=rl;para(8)=zs;para(9)=dz;para(10)=zl;
    para(11)=dt;para(12)=td;para(13)=pn; para(14)=i_now;para(15)=power_Joule;para(16)=bz_max;para(17)=B0_correction_factor
    para(18)=i_switch_B0

    para(20)=np_ini;para(21)=it;para(23)=dt;para(24)=td;para(25)=trf;
    para(26)=i_switch_B0;para(29)=za;para(30)=ra;
    para(31)=z_inject;para(32)=vi_ex;para(33)=ve_ex;para(34)=B_resonance
    para(35)=mi;para(36)=me;para(37)=n_macro

502 format(e12.4,' ')
    open (unit=75,file='1parameter.dat',status='unknown',iostat=ierror)
    write (75,502)para
    close(75)
    endsubroutine rec_para



    subroutine set_particle_inject_distribution
    use the_whole_varibles
    implicit none
    real*8  :: ni_int,volume,ni_bd
    real*8  :: sr(1:nr_ion),sz(1:nz),sr_half(2:nr_ion),sz_half(2:nz)

    ni_bd=1e17; !m-3
    !set initial plasma
    ! Gaussian distribution: ni(r,z)=n0*exp(-r^2/(2*rw^2))*exp(-(z-zc)^2/(2*zw^2))
    z_peak_ne=z_inject !zc
    ne=1e7; !initial set to avoid null value
    do ir=1,nr_ion
        do iz=1,nz
            !if(i_plasma_region(ir,iz)>0.5)then
            tp1=exp(-r(ir)**2/(2*width_ne_r**2));
            tp2=exp(-(z(iz)-z_peak_ne)**2/(2*width_ne_z**2));
            ne(ir,iz)=ni_bd+max_density_set*(tp1*tp2);

            !exp distribution
            sr(ir)=1+max_density_set/ni_bd*tp1
            sz(iz)=1+max_density_set/ni_bd*tp2

            !!uniform source term
            !sr(ir)=1
            !sz(iz)=1
            !endif
        enddo
    enddo
    sr(1)=0;sr(nr_ion)=0;
    sz(1)=0;sz(nz)=0;

    !ne=ni;
    te=te_ini

    sr_half(2:nr_ion)=0.5*(sr(1:nr_ion-1)+sr(2:nr_ion))
    sz_half(2:nz)=0.5*(sz(1:nz-1)+sz(2:nz))
    sr_half=sr_half/maxval(sr_half)
    sz_half=sz_half/maxval(sz_half)

    !PDF: density distribution probability
    ir=1;pdf_ne_r(ir)=0;
    ir=2;pdf_ne_r(ir)=pi*((dr_ion*0.5)**2)*sr_half(ir)
    do ir=3,nr_ion-1
        pdf_ne_r(ir)=pdf_ne_r(ir-1)+2*pi*(r2(ir)**2-r2(ir-1)**2)*sr_half(ir)
    enddo
    ir=nr_ion;pdf_ne_r(ir)=pdf_ne_r(ir-1)+2*pi*(r(ir)**2-r2(ir-1)**2)*sr_half(ir)
    pdf_ne_r=pdf_ne_r/maxval(pdf_ne_r) !normalization
    do ir=1,nr_ion
        if(abs(pdf_ne_r(ir)-1.)<1e-20)then
            pdf_ne_r(ir+1:nr_ion)=2
            exit
        endif
    enddo

    iz=1;pdf_ne_z(iz)=0.
    iz=2;pdf_ne_z(iz)=0.5*dz*sz_half(iz)
    do iz=3,nz-1
        pdf_ne_z(iz)=pdf_ne_z(iz-1)+dz*sz_half(iz) !
    enddo
    iz=nz;pdf_ne_z(iz)=pdf_ne_z(iz-1)+0.5*dz*sz_half(iz)
    pdf_ne_z=pdf_ne_z/maxval(pdf_ne_z) !normalization

    do iz=1,nz
        if(abs(pdf_ne_z(iz)-1.)<1e-20)then
            pdf_ne_z(iz+1:nz)=2
            exit
        endif
    enddo

    !set plasma souce (inject with time)
    !plasma souce in z direction
    !set initial plasma
    ! Gaussian distribution: ni(r,z)=n0*exp(-r^2/(2*rw^2))*exp(-(z-zc)^2/(2*zw^2))
    pdf_ne_source_r=pdf_ne_r

    do iz=1,nz
        tp2=exp(-(z(iz)-z_peak_ne)**2/(2*width_ne_source_z**2));
        sz(iz)=1+max_density_set/ni_bd*tp2
    enddo
    sz_half(2:nz)=0.5*(sz(1:nz-1)+sz(2:nz))
    sz_half=sz_half/maxval(sz_half)

    iz=1;pdf_ne_source_z(iz)=0.
    iz=2;pdf_ne_source_z(iz)=0.5*dz*sz_half(iz)
    do iz=3,nz-1
        pdf_ne_source_z(iz)=pdf_ne_source_z(iz-1)+dz*sz_half(iz) !
    enddo
    iz=nz;pdf_ne_source_z(iz)=pdf_ne_source_z(iz-1)+0.5*dz*sz_half(iz)
    pdf_ne_source_z=pdf_ne_source_z/maxval(pdf_ne_source_z) !normalization

    do iz=1,nz
        if(abs(pdf_ne_source_z(iz)-1.)<1e-20)then
            pdf_ne_source_z(iz+1:nz)=2
            exit
        endif
    enddo

    !normalization
    ds=dr*dz
    ni_int=0.
    do iz=1,nz-1
        do ir=1,nr_ion-1
            ni_int=ni_int+2*pi/max_density_set*1./4.*(ne(ir,iz)*r(ir)+ne(ir+1,iz)*r(ir+1) &
                &               +ne(ir,iz+1)*r(ir)+ne(ir+1,iz+1)*r(ir+1))*ds
        end do
    end do

    volume=pi*r_ion_max**2*zl
    ni_ave_ratio=ni_int/volume
    n_macro=volume*ni_ave_ratio*max_density_set/np_max !n_macro=ni_int/np_max
    density_ave=ni_ave_ratio*max_density_set  !m-3

    endsubroutine set_particle_inject_distribution




    subroutine set_ne_Te
    use the_whole_varibles
    implicit none

    ne=1e7;te=0.2
    do ir=1,nr
        do iz=1,nz
            if(i_plasma_region(ir,iz)>0.5)then
                !tp1=exp(-r(ir)**2/(2.0d0*width_ne_source_r**2));
                !tp2=exp(-(z(iz)-z_inject)**2/(2.0d0*width_ne_source_z**2));
                ne(ir,iz)=n_macro*density_2D(ir,iz);        !the area the PIC module not simulate
                te(ir,iz)=te_2D(ir,iz)
            endif
        enddo
    enddo
    endsubroutine set_ne_Te


    subroutine fdfd_ini
    use the_whole_varibles
    implicit none    
    !----------------------- By Xuad in 0124 -----------------------!
    if(iswitch_antenna_type==0)then
        m_start=0
        m_end=-m_start
        m_delta=+2
    else
        m_start=-15
        m_end=-m_start
        m_delta=+1
    endif
    
    
    switch_plasma_vacuum_boundary=43 !switch boundary of plasma-vacuum rp; 0:nothing more; 1:tangent continuous ;2:tangent continuous + Div(E)=0(vacuum);
    !3 :tangent continuous + Div(E)=0 + Jpn=0
    !4 :tangent continuous + Div(E)=0 + pdv{Dn}{r}continuous
    !5 :tangent continuous + Div(E)=0 + Dn condinuous
    !7 :tangent continuous + Div(E)=0[outside] + Div(D)=0[inside]
    !8 :tangent continuous + B_th continuous
    !1X : only Ez continuous + X[don't use]
    !2X : X + Ez continuous
    !!!!!!!!!!!!!!!!!!!!!!!switch_plasma_vacuum_boundary �� ep û�в�ֵ!!!!!!!!!!!!!!!!!!!!!!
    switch_z_boundary=1 ! switch boundary condition of z=0/l; 1:conductor Boundary  ;  ; 3: z=0:conductor;z=zl:absorbing(For Vacuum Benchmark)
    switch_boundary_half_variables=1 !Switch how to handle variables on half Grid in boundaries.
    !0 : by eqs(inside) or extrapolation (outside);
    !1: Interpolation/Extrapolation to find it's quantity or derivative at boundary
    switch_r_0_boundary=1   !Switch how to handle the boundary condition of r=0. 1:old 2:new;
    switch_source_type=1 !0: z=0 Source(For Benchmark) 1:Antenna
    switch_divE=2!  0: ignore div(E) ; 1:not ignore div(E)(div(E) neq ===0); 2:ignore div(E) in Vacuum and nod ignore in Plasma Area
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!MUST NOT SET IT TO 0 (Except TESTing)
    endsubroutine fdfd_ini
